export type GuideSection = { id: string; title: string; paragraphs: string[]; points?: string[] };
export type GuideFaq = { q: string; a: string };
export type PropertyGuide = { slug: string; title: string; seoTitle: string; description: string; summary: string; target: string; targetLabel: string; sections: GuideSection[]; faqs?: GuideFaq[]; sources: { label: string; url: string }[] };
export const propertyGuides: PropertyGuide[] = [
  {
    slug: 'what-is-lease-management-software',
    title: 'What is lease management software?',
    seoTitle: 'What Is Lease Management Software? | Hobson',
    description: 'Understand lease management software, key dates, lease abstraction and evidence checks, with a practical checklist for UK property teams.',
    summary: 'Lease management software brings lease records, important dates and contractual obligations into one place. It helps a property team understand what has been agreed, what needs attention and which document supports the answer.',
    target: '/lease-management-software', targetLabel: 'Explore Hobson lease management software',
    sections: [
      { id: 'what-it-does', title: 'What does it actually do?', paragraphs: ['A lease is more than a file to store. It records parties, premises, rent, review mechanisms, repair responsibilities, break rights and conditions. Lease management software organises these details so they can be searched, reviewed and used in day-to-day work.', 'The scope varies by product. Some systems emphasise date reminders and reporting; others include financial administration, document extraction or lease accounting. Do not assume that a product described as lease management software includes all of these.'], points: ['Keep lease documents and records together.', 'Record rent reviews, breaks and expiry dates with their conditions.', 'Find obligations and allocate follow-up work.', 'Report across leases rather than opening each file separately.'] },
      { id: 'different-tools', title: 'Lease management, property management and abstraction', paragraphs: ['Property management software has a broader operational remit: depending on the product, it may cover rent collection, maintenance, tenant communication and accounting. Lease management concentrates on the agreement and the obligations it creates.', 'Lease abstraction is a narrower task: extracting selected terms from a lease into a structured summary. It can supply the information used in a lease management system, but a summary alone does not manage the ongoing relationship.', 'Lease accounting is another distinct requirement. If you need IFRS 16 calculations or accounting outputs, ask for a demonstration of those functions specifically. Document extraction is not a substitute for an accounting engine.'] },
      { id: 'example', title: 'A break date is not just a date', paragraphs: ['Imagine a team asking when a tenant can end a lease. A useful record needs more than the break date: it may need a notice period, a service method and conditions that affect whether the right can be exercised.', 'The team should check the original clause and any later documents before acting. A deed of variation may change the position. A system should make that evidence accessible, not encourage a decision based only on a calendar entry.', 'This example is illustrative, not legal advice. A qualified adviser should review legal interpretation and formal notices.'] },
      { id: 'choosing', title: 'What to check in a demonstration', paragraphs: ['Use a representative lease from your own portfolio, with permission to share it. Include a later variation and a question whose answer you already know. This reveals more than a polished demonstration using a simple sample.'], points: ['Can you trace a value back to the exact passage and page?', 'Can the system distinguish a missing fact from a confirmed answer?', 'How are variations and related documents connected?', 'Who reviews extracted information and approves actions?', 'Can you export records and supporting evidence when you leave?', 'What access controls, retention terms and support arrangements apply?'] },
      { id: 'hobson', title: 'Where Hobson fits', paragraphs: ['Hobson focuses on reading property documents, structuring what they say and answering questions with Exact Extracts. Its Business Memory connects source material to the property context, organised as Portfolio > Unit Group > Unit.', 'That makes Hobson relevant when the bottleneck is finding and checking what a lease says. It is not a claim that Hobson replaces every accounting, maintenance or agency system. Preparation is mine, decision is yours: the team remains responsible for checking evidence and confirming consequential decisions.'] },
    ],
    faqs: [
      { q: 'What is lease management software?', a: 'Software that brings lease records, important dates and contractual obligations into one place, so a property team can see what has been agreed, what needs attention and which document supports the answer.' },
      { q: 'Is lease management software the same as property management software?', a: 'No. Property management software has a broader operational remit, such as rent collection, maintenance and tenant communication. Lease management concentrates on the agreement itself and the obligations it creates.' },
      { q: 'Is lease abstraction the same as lease management?', a: 'No. Lease abstraction is the narrower task of extracting selected terms from a lease into a structured summary. That summary can feed a lease management system, but it does not manage the ongoing relationship by itself.' },
      { q: 'Does lease management software replace lease accounting?', a: 'Not necessarily. If you need IFRS 16 calculations or accounting outputs, ask for a demonstration of those functions specifically. Document extraction is not a substitute for an accounting engine.' },
      { q: 'What should I check in a demonstration?', a: 'Use a real lease from your own portfolio, with a later variation and a question whose answer you already know. Check whether you can trace a value back to the exact passage and page, how variations are connected, and who reviews extracted information before action is taken.' },
    ],
    sources: [{ label: 'MRI Software: what is lease management?', url: 'https://www.mrisoftware.com/uk/blog/what-is-lease-management/' }, { label: 'Accruent: what is lease management?', url: 'https://www.accruent.com/resources/knowledge-hub/what-is-lease-management' }],
  },
  {
    slug: 'how-much-does-property-management-software-cost',
    title: 'How much does property management software cost?',
    seoTitle: 'Property Management Software Cost UK | Hobson',
    description: 'Compare UK property software pricing models, setup costs and contract questions. Understand Hobson’s document learning and seat pricing.',
    summary: 'There is no single UK price: the cost depends on the number of properties or people, the work included and the effort needed to set up your records. Compare the first-year total, not just the headline monthly subscription.',
    target: '/pricing', targetLabel: 'Calculate your Hobson pricing',
    sections: [
      { id: 'pricing-models', title: 'The four pricing models to recognise', paragraphs: ['Per-unit pricing grows with the number of properties or units managed. Check minimum charges and what the supplier counts as a unit, particularly for shared premises or mixed-use buildings.', 'Per-seat pricing grows with the number of people using the system. Check whether occasional reviewers, external advisers and administrators need paid seats.', 'Tiered subscriptions bundle capacity and functionality. A low starting price may exclude reporting, integrations or support that your team needs.', 'Quote-based pricing is common where configuration and portfolio complexity matter. Ask for a written breakdown so implementation and recurring charges can be compared separately.'] },
      { id: 'first-year', title: 'Build a first-year budget', paragraphs: ['Use this calculation: first-year cost = setup and migration + document preparation or learning + subscription payments + required extras. Include VAT where applicable and allow for internal staff time.', 'Ask whether the advertised price assumes annual payment, whether renewal pricing changes and what happens if your portfolio grows. A monthly equivalent on an annual contract is not the same as a cancellable monthly subscription.'], points: ['Migration, data cleaning and document preparation.', 'User training and implementation support.', 'Required integrations, storage and usage allowances.', 'Additional people, properties or newly added documents.', 'Export, cancellation and renewal terms.'] },
      { id: 'hobson-cost', title: 'How Hobson prices the work', paragraphs: ['Hobson’s current public pricing separates one-off document learning from ongoing seats. The page shows £35 per person per month, with the complete product rather than feature-gated seat tiers.', 'The document calculator shows an estimated reading range of £0.25–£0.40 per document. This is an estimate, not a fixed quotation: the reading fee needs approval before work begins. Human Concierge document preparation is shown separately at £2.50 per document, with a ten-document minimum; do not confuse that service with the automated reading estimate.', 'For illustration, four standard seats are £140 per month. Reading 1,000 documents at the displayed estimate would be £250–£400 once. Twelve paid seat months plus that reading estimate would total £1,930–£2,080 before any applicable tax, optional services or offers.', 'The Pricing page also describes the Together offer, under which the first month of seats is waived once the reading fee is approved. The example above deliberately excludes offers. Use the live calculator and confirm tax treatment, service scope and terms in your quote.'] },
      { id: 'compare-quotes', title: 'Compare quotes on the same basis', paragraphs: ['Arthur publishes unit-based plans, Landlord Vision publishes portfolio-based plans, and Re-Leased provides tailored pricing. Their scope differs, so dividing each quote by the number of properties is not enough to establish value.', 'Give suppliers the same brief: portfolio size, number of users, document volume, required workflows, accounting tools and implementation date. Ask each to identify both what is included and what would need another system.', 'Vendor prices can change. The official pricing pages below are the place to check current amounts and terms; this guide does not reproduce temporary discounts or claim a market-wide price range.'] },
      { id: 'value', title: 'Measure value against a real task', paragraphs: ['Choose a repeatable task such as checking a rent review clause across a set of leases. Record the time spent finding documents, verifying answers and preparing the result. Then repeat the task during a supervised trial.', 'Any saving should be measured rather than assumed. A cheaper subscription is not better value if it leaves the important work manual; a more expensive one is not justified by features your team will never use.'] },
    ],
    faqs: [
      { q: 'How much does property management software cost in the UK?', a: 'There is no single UK price. The cost depends on the number of properties or people, the work included and the effort needed to set up your records. Compare the first-year total — setup, migration, subscription and required extras — not just the headline monthly subscription.' },
      { q: 'What pricing models do suppliers use?', a: 'The four common models are per-unit pricing, per-seat pricing, tiered subscriptions and quote-based pricing. Each grows differently as your portfolio or team changes, so ask how minimum charges and renewals work in each case.' },
      { q: 'How much does Hobson cost?', a: 'Hobson’s public pricing is £35 per person per month for the complete product, plus a one-off document reading estimate of £0.25–£0.40 per document. Human Concierge document preparation is a separate optional service. Use the live calculator on the Pricing page for current figures.' },
      { q: 'How should I compare quotes from different suppliers?', a: 'Give each supplier the same brief: portfolio size, number of users, document volume, required workflows and implementation date. Ask each to identify what is included and what would need another system, then compare full first-year costs and renewal terms.' },
      { q: 'Is the cheapest software the best value?', a: 'Not necessarily. A cheaper subscription is not better value if it leaves the important work manual, and a more expensive one is not justified by features your team will never use. Measure value against a real, repeatable task before deciding.' },
    ],
    sources: [{ label: 'Hobson: current pricing and calculators', url: '/pricing' }, { label: 'Arthur: pricing', url: 'https://www.arthuronline.co.uk/pricing' }, { label: 'Landlord Vision: pricing', url: 'https://www.landlordvision.co.uk/landlord-software-pricing.html' }, { label: 'Re-Leased: pricing', url: 'https://www.re-leased.com/en-gb/pricing' }],
  },
  {
    slug: 'best-property-management-software-uk',
    title: 'Best property management software UK: choosing the right fit',
    seoTitle: 'Best Property Management Software UK: A Guide | Hobson',
    description: 'A practical UK buyer’s guide comparing property software by job: residential operations, commercial portfolios, landlord finances and document evidence.',
    summary: 'The best property management software is the one that handles your team’s actual work. A residential landlord, a commercial asset manager and a team checking complex leases may need very different tools.',
    target: '/property-management-software', targetLabel: 'Explore Hobson property management software',
    sections: [
      { id: 'method', title: 'How to use this shortlist', paragraphs: ['This guide is published by Hobson, one of the products discussed. It is not an independent ranking or a hands-on test. The shortlist uses the official product and pricing pages linked below to distinguish use cases, not award scores.', 'It is selective, not exhaustive. Product capabilities, packages and availability should be confirmed directly with each supplier. No product is named an overall winner, and no absence from the shortlist implies poor quality.'] },
      { id: 'landlord-vision', title: 'Landlord Vision — landlord finances and records', paragraphs: ['Landlord Vision presents software for landlords with rent tracking, expense management and property records. It is worth considering when financial administration and keeping rental records organised are central to the brief.', 'Ask the supplier to demonstrate your ownership structure, reconciliation workflow and reporting requirements. If Making Tax Digital is a requirement, confirm the current supported service and whether it fits your circumstances rather than relying on a general compliance label.'] },
      { id: 'arthur', title: 'Arthur — residential property operations', paragraphs: ['Arthur presents a property management platform with apps for tenants, contractors and owners, alongside unit-based pricing. It belongs on a shortlist where coordinating people and operational tasks matters.', 'Demonstrate a maintenance request from initial report to completion. Check which package includes the workflow, accounting connection and access each participant requires, and how minimum unit charges affect your total.'] },
      { id: 're-leased', title: 'Re-Leased — commercial and mixed-use portfolios', paragraphs: ['Re-Leased positions its platform around commercial property management, with lease administration and financial workflows. Its UK site describes service charge budgeting and accounting integrations.', 'Ask it to demonstrate your rent schedules, service charge structure and accounting hand-off. Pricing is tailored, so request the implementation scope and ongoing charges together rather than comparing an unspecified quote with another supplier’s entry plan.'] },
      { id: 'hobson', title: 'Hobson — document-grounded property knowledge', paragraphs: ['Hobson is relevant where the difficult work is understanding leases and related documents. Its emphasis is Business Memory, structured extraction and evidence-backed answers rather than simply storing a document or a typed summary.', 'Use a lease and a later variation to test how an answer is supported by Exact Extracts. Ask how the team reviews results and confirms decisions. Check availability and suitability with Hobson before planning adoption; this guide does not promise that it replaces rent accounting, maintenance dispatch or a letting agency CRM.'] },
      { id: 'test', title: 'Give every supplier the same test', paragraphs: ['Write a short brief before booking demonstrations. Describe the portfolio and the three tasks taking the most time. Decide which requirements are essential and which are optional.'], points: ['Use the same permitted sample documents and known answers.', 'Test an exception, not just the simplest workflow.', 'Check permissions for colleagues and outside advisers.', 'Request data protection, retention and export information.', 'Compare full first-year costs and renewal terms.', 'Agree who checks information and approves consequential actions.'] },
      { id: 'decision', title: 'Choose the workflow before the software', paragraphs: ['If the pain is bookkeeping, prioritise financial workflows. If it is operational coordination, prioritise the people and task journey. If it is understanding what documents actually say, prioritise source evidence and review.', 'You may need complementary systems rather than a single replacement. Verify any proposed integration before purchase; the fact that two tools serve the same portfolio does not mean they exchange data automatically.'] },
    ],
    sources: [{ label: 'Landlord Vision: rent tracking and expense management', url: 'https://www.landlordvision.co.uk/rent-tracking-and-expense-management.html' }, { label: 'Arthur: product and packages', url: 'https://www.arthuronline.co.uk/pricing' }, { label: 'Re-Leased: UK product overview', url: 'https://www.re-leased.com/en-gb/' }, { label: 'Re-Leased: budget management', url: 'https://www.re-leased.com/en-gb/product/budget-management' }, { label: 'Hobson: property management software', url: '/property-management-software' }],
  },
];
