// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awfyhgeflakjhxtntokd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3ZnloZ2VmbGFramh4dG50b2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzQxOTQsImV4cCI6MjA2ODY1MDE5NH0.fsL80w5qqlLaZ2p3SSsX2dhPO1e8DoJXkNjSAShYlfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});